---
head_title: Marek C | Blog
email: contact@jay23.com
author: Marek Cieśla
description: Marek Cieśla - Head of business development. Serial kickstarter.
keywords: Marek, Ciesla, Blog, kickstarter, mimi, mimigroup, startup
baseurl: ''
url: https://blog.jay23.com
date_format: "%b %-d, %Y"
structured_date_format: "%Y-%m-%d"
grammarly_link: https://grammarly.com
digital_ocean_link: https://www.digitalocean.com/
abot_link: https://abot.app
email_subscription_link: https://mailchimp.com/
header_pages:
- pages/home.html
- pages/about.md
google_verification: 
google_tag_manager: 
animated: false
show_post_footers: true
show_social_icons: true
post_preview_image: false
disqus_shortname: marekciesla
github_username: lancelotek
twitter_username: marekciesla
linkedin_username: 
medium_id: 
flattr_button: 
show_sharing_icons: true
share_twitter: true
share_facebook: true
text:
  pagination:
    newer: Newer
    older: Older
  share_buttons:
    text: 'Share:'
    twitter: Share on Twitter
    facebook: Share on Facebook
  post:
    updated: Updated
    minute_read: minute read
    related_posts: Related Posts
  index:
    coming_soon: Coming soon...
  contact:
    email: ''
    content: ''
    subject: New submission!
    submit: Send
    ajax:
      sending: sending..
      sent: Message sent!
      error: Error!
  og_locale: en_US
markdown: kramdown
redcarpet:
  extensions:
  - smart
  - tables
  - with_toc_data
permalink: "/:title"
paginate: "9"
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-assets
exclude:
- Gemfile
- Gemfile.lock
- vendor
- deploy.sh
- certificates.tar
- app-nginx.conf.sigil
- purge.rb
- CHECKS
- app.json
- ".env"
- Rakefile
- README.md
defaults:
- scope:
    path: files/*.pdf
  values:
    sitemap: false
- scope:
    path: build/
  values:
    sitemap: false
assets:
  defaults:
    js:
      integrity: false
    css:
      integrity: false
    img:
      integrity: false
  digest: true
  sources:
  - _assets/css
  - _assets/css/scss
  - _assets/images/shared
