---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Foo
- type: directory
  path: ''
  label: Bar Baz
  create: all
  match: "**/*"
upload_dir: _assets/images
public_path: "/_assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: gem install bundler && bundle install --path vendor/bundle
    && npm install
  preview_docker_image: forestryio/ruby:2.6-node12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
